# Generated by Django 5.0.6 on 2024-06-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_course",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_lesson",
            new_name="lesson",
        ),
    ]
